# These are supported funding model platforms

# github: XenchinRyu7
# patreon: # your patreon username
# open_collective: # your open collective username
# ko_fi: # your ko-fi username
# tidelift: # your tidelift package
# community_bridge: # your community bridge project name
# liberapay: # your liberapay username
# issuehunt: # your issuehunt username
# custom: # your custom sponsorship URL
